###
POST http://localhost:8080/api/register HTTP/1.1
User-Agent: rest-client
content-type: application/json

{
"photo" :"",
"username" :"username15773",
"email" :"string@gmail.com",
"password" :"rfdfdfd",
"description" :"lorem454656456",
"visibility":true
}

###
POST http://localhost:8080/api/login HTTP/1.1
User-Agent: rest-client
content-type: application/json

{
"email" :"string@gmail.com",
"password" :"lkjdjh464549uh"
}


###
GET http://localhost:8080/api/users HTTP/1.1
User-Agent: rest-client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvdG8iOm51bGwsInVzZXJuYW1lIjoidXNlcm5hbWUxNTc3MyIsImVtYWlsIjoic3RyaW5nQGdtYWlsLmNvbSIsImRlc2NyaXB0aW9uIjpudWxsLCJ2aXNpYmlsaXR5IjoxLCJpYXQiOjE3NDE4Nzc1MDgsImV4cCI6MTc0MTk2MzkwOCwiYXVkIjoiSE4iLCJpc3MiOiJIYWNrZXJOZXdzIn0.Z5es63Iulll-aRNUaCeDV19hvqumDPbWpdTxAI5m5CQ

###
POST http://localhost:8080/api/favorite-story HTTP/1.1
User-Agent: rest-client
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvdG8iOm51bGwsInVzZXJuYW1lIjoidXNlcm5hbWUxNTc3MyIsImVtYWlsIjoic3RyaW5nQGdtYWlsLmNvbSIsImRlc2NyaXB0aW9uIjpudWxsLCJ2aXNpYmlsaXR5IjoxLCJpYXQiOjE3NDE4Nzc1MDgsImV4cCI6MTc0MTk2MzkwOCwiYXVkIjoiSE4iLCJpc3MiOiJIYWNrZXJOZXdzIn0.Z5es63Iulll-aRNUaCeDV19hvqumDPbWpdTxAI5m5CQ

{
"storyId" :1718,
"action" :"add"
}

###
GET  http://localhost:8080/api/favorite-stories HTTP/1.1
User-Agent: rest-client
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvdG8iOm51bGwsInVzZXJuYW1lIjoidXNlcm5hbWUxNTc3MyIsImVtYWlsIjoic3RyaW5nQGdtYWlsLmNvbSIsImRlc2NyaXB0aW9uIjpudWxsLCJ2aXNpYmlsaXR5IjoxLCJpYXQiOjE3NDE4Nzc1MDgsImV4cCI6MTc0MTk2MzkwOCwiYXVkIjoiSE4iLCJpc3MiOiJIYWNrZXJOZXdzIn0.Z5es63Iulll-aRNUaCeDV19hvqumDPbWpdTxAI5m5CQ


###
PATCH http://localhost:8080/api/profil HTTP/1.1
User-Agent: rest-client
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvdG8iOm51bGwsInVzZXJuYW1lIjoidXNlcm5hbWUxNTc3MyIsImVtYWlsIjoic3RyaW5nQGdtYWlsLmNvbSIsImRlc2NyaXB0aW9uIjpudWxsLCJ2aXNpYmlsaXR5IjoxLCJpYXQiOjE3NDE4Nzc1MDgsImV4cCI6MTc0MTk2MzkwOCwiYXVkIjoiSE4iLCJpc3MiOiJIYWNrZXJOZXdzIn0.Z5es63Iulll-aRNUaCeDV19hvqumDPbWpdTxAI5m5CQ

{
"username":"username15773",
"email":"string@gmail.com",
"description" :"lorem454656456",
"visibility":true
}
###
PATCH http://localhost:8080/api/password HTTP/1.1
User-Agent: rest-client
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGhvdG8iOm51bGwsInVzZXJuYW1lIjoidXNlcm5hbWUxNTc3MyIsImVtYWlsIjoic3RyaW5nQGdtYWlsLmNvbSIsImRlc2NyaXB0aW9uIjpudWxsLCJ2aXNpYmlsaXR5IjoxLCJpYXQiOjE3NDE4Nzc1MDgsImV4cCI6MTc0MTk2MzkwOCwiYXVkIjoiSE4iLCJpc3MiOiJIYWNrZXJOZXdzIn0.Z5es63Iulll-aRNUaCeDV19hvqumDPbWpdTxAI5m5CQ

{
"password" :"lkjdjh464549uh"
}